### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by minwook-shin** [minwook-shin/ubuntu-ko-irc-in-python#1]
- [x] 슬랙 표시 작업

- [x] 이모티콘 표시

- [ ] 파일 분할 작업

- [x] GUI 프로그램 제작

- [ ] 서버 전용 응용 프로그램 제작

- [ ] 윈도우용 프로그램 제작

- [ ] API 제작
